a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
print('The addition of the numbers is: ', a+b)
print('The subtraction of the numbers is: ',abs( a-b))
print('The multiplication of the numbers is: ', a*b)
print('The division of the numbers is: ', (a/b))
